package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import database.DBManager;
import database.SQLConstants;
import database.SQLQueries;
import entities.Receipt;
import entities.ReceiptService;
import entities.Status;
import entities.User;
import exceptions.ReceiptException;

/**
 * @author Viktor Shutko
 * @description class that implements special API for working with database
 *              entity 'Receipt'
 * @provides static methods for manipulating 'Receipt' entity
 * @uses Receipt.class, User.class, ReceiptService.class
 */
public class ReceiptDAO {
	/**
	 * provides connection to database
	 */
	private static DBManager connector;

	/**
	 * @param u               - User.class
	 * @param receiptServices - ReceiptServices.class
	 * @return receiptId, generated by DBMS
	 * @throws ReceiptException
	 */
	public static long addReceipt(User u, ReceiptService... receiptServices) throws ReceiptException {
		connector = DBManager.getInstance();
		Connection connection = null;
		PreparedStatement receiptPst = null;
		PreparedStatement receiptServicePst = null;
		ResultSet rs = null;
		Timestamp date = new Timestamp(new Date().getTime());
		long generatedId = 0;
		int k = 0;
		try {
			connection = connector.getConnection();
			connection.setAutoCommit(false);
			receiptPst = connection.prepareStatement(SQLQueries.INSERT_NEW_RECEIPT,
					PreparedStatement.RETURN_GENERATED_KEYS);
			receiptPst.setLong(++k, u.getId());
			receiptPst.setTimestamp(++k, date, Receipt.getCalendar());
			receiptPst.setLong(++k, SQLConstants.INITIAL_STATUS);
			receiptPst.executeUpdate();
			rs = receiptPst.getGeneratedKeys();
			if (rs.next()) {
				generatedId = rs.getLong(1);
			}
			receiptServicePst = connection.prepareStatement(SQLQueries.INSERT_RECEIPT_SERVICE);
			for (int i = 0; i < receiptServices.length; i++) {
				receiptServices[i].setReceiptId(generatedId);
				receiptServicePst.setLong(1, receiptServices[i].getReceiptId());
				receiptServicePst.setLong(2, receiptServices[i].getServiceId());
				receiptServicePst.setDouble(3, receiptServices[i].getServicePrice());
				receiptServicePst.executeUpdate();
			}
			connection.commit();
		} catch (SQLException e) {
			DBManager.doRollback(connection);
			e.printStackTrace();
			throw new ReceiptException("Error creating a receipt");
		} finally {
			DBManager.close(rs);
			DBManager.close(receiptPst);
			DBManager.close(receiptServicePst);
			DBManager.close(connection);
		}
		return generatedId;
	}

	public static void setAdminForReceipt(User admin, Receipt receipt) throws ReceiptException {
		connector = DBManager.getInstance();
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.SET_ADMIN_FOR_RECEIPT);) {
			pst.setLong(1, admin.getId());
			pst.setLong(2, receipt.getId());
			pst.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error adding admin to receipt");
		}
	}

	public static void setMasterForReceipt(User master, Receipt receipt) throws ReceiptException {
		connector = DBManager.getInstance();
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.SET_MASTER_FOR_RECEIPT);) {
			pst.setLong(1, master.getId());
			pst.setLong(2, receipt.getId());
			pst.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error adding master to receipt");
		}
	}

	public static Receipt getReceiptById(long id) throws ReceiptException {
		connector = DBManager.getInstance();
		Receipt r = null;
		ResultSet rs = null;
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.GET_RECEIPT_BY_ID)) {
			pst.setLong(1, id);
			rs = pst.executeQuery();
			if (rs.next()) {
				r = mapReceipt(rs);
			} else
				throw new ReceiptException("No such receipt with id = " + id);
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error getting receipt");
		} finally {
			DBManager.close(rs);
		}
		return r;
	}

	public static List<Receipt> getAllReceipts() throws ReceiptException {
		connector = DBManager.getInstance();
		List<Receipt> receipts = new ArrayList<>();
		try (Connection connection = connector.getConnection();
				Statement st = connection.createStatement();
				ResultSet rs = st.executeQuery(SQLQueries.GET_ALL_RECEIPTS)) {
			while (rs.next()) {
				receipts.add(mapReceipt(rs));
			}
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error getting list of receipts!");
		}
		return receipts;
	}

	public static void setReceiptTotalSum(Receipt r, double sum) throws ReceiptException {
		if (sum < 0) {
			throw new ReceiptException("Error. Sum cannot be negative!");
		}
		connector = DBManager.getInstance();
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.SET_RECEIPT_TOTAL_SUM)) {
			pst.setDouble(1, sum);
			pst.setLong(2, r.getId());
			pst.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error defining receipt sum!");
		}
	}

	public static double getReceiptTotalSum(Receipt r) throws ReceiptException {
		connector = DBManager.getInstance();
		double totalSum = -1;
		ResultSet rs = null;
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.GET_RECEIPT_TOTAL_SUM)) {
			pst.setLong(1, r.getId());
			rs = pst.executeQuery();
			if (rs.next()) {
				totalSum = rs.getDouble(SQLConstants.TOTAL_SUM);
			}
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error getting receipt " + r.getId() + " total sum!");
		} finally {
			DBManager.close(rs);
		}
		return totalSum;
	}

	private static Receipt mapReceipt(ResultSet rs) throws SQLException {
		Receipt r = new Receipt();
		r.setId(rs.getLong(SQLConstants.ID_RECEIPT));
		r.setAdminId(rs.getLong(SQLConstants.ID_ADMIN));
		r.setMasterId(rs.getLong(SQLConstants.ID_MASTER));
		r.setTotalSum(rs.getDouble(SQLConstants.TOTAL_SUM));
		r.setStatus(rs.getLong(SQLConstants.ID_STATUS));
		r.setUserId(rs.getLong(SQLConstants.ID_USER));
		r.setDate(rs.getTimestamp(SQLConstants.REC_DATE, Receipt.getCalendar()));
		return r;
	}

	public static User getReceiptUser(long receiptId) throws ReceiptException {
		User u = null;
		ResultSet rs = null;
		connector = DBManager.getInstance();
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.GET_RECEIPT_USER)) {
			pst.setLong(1, receiptId);
			rs = pst.executeQuery();
			if (rs.next()) {
				u = UserDAO.mapUser(rs);
			}
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("No such user found");
		} finally {
			DBManager.close(rs);
		}
		return u;
	}

	public static User getReceiptAdmin(long receiptId) throws ReceiptException {
		User u = null;
		ResultSet rs = null;
		connector = DBManager.getInstance();
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.GET_RECEIPT_ADMIN)) {
			pst.setLong(1, receiptId);
			rs = pst.executeQuery();
			if (rs.next()) {
				u = UserDAO.mapUser(rs);
			}
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("No such user found");
		} finally {
			DBManager.close(rs);
		}
		return u;
	}

	public static User getReceiptMaster(long receiptId) throws ReceiptException {
		User u = null;
		ResultSet rs = null;
		connector = DBManager.getInstance();
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.GET_RECEIPT_MASTER)) {
			pst.setLong(1, receiptId);
			rs = pst.executeQuery();
			if (rs.next()) {
				u = UserDAO.mapUser(rs);
			}
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("No such user found");
		} finally {
			DBManager.close(rs);
		}
		return u;
	}

	public static void removeReceiptById(long id) throws ReceiptException {
		connector = DBManager.getInstance();
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.REMOVE_RECEIPT)) {
			pst.setLong(1, id);
			pst.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error removing receipt with id = " + id + "!");
		}
	}

	public static List<Receipt> getReceiptsByStatus(long idstatus) throws ReceiptException {
		connector = DBManager.getInstance();
		List<Receipt> receipts = new ArrayList<>();
		ResultSet rs = null;
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.GET_RECEIPTS_BY_STATUS)) {
			pst.setLong(1, idstatus);
			rs = pst.executeQuery();
			while (rs.next()) {
				receipts.add(mapReceipt(rs));
			}
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error getting receipts by status " + idstatus + "!");
		} finally {
			DBManager.close(rs);
		}
		return receipts;
	}

	public static void updateReceiptStatusByReceiptId(long idreceipt, int idstatus) throws ReceiptException {
		connector = DBManager.getInstance();
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.UPDATE_RECEIPT_STATUS)) {
			pst.setInt(1, idstatus);
			pst.setLong(2, idreceipt);
			pst.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error updating receipt no " + idreceipt);
		}
	}

	public static List<Receipt> getAllReceiptsOrderedByDate(boolean DESC) throws ReceiptException {
		connector = DBManager.getInstance();
		List<Receipt> receipts = new ArrayList<>();
		ResultSet rs = null;
		PreparedStatement pst = null;
		try (Connection connection = connector.getConnection()) {
			if (DESC) {
				pst = connection.prepareStatement(SQLQueries.GET_RECEIPTS_ORDER_BY_DATE_DESC);
			} else {
				pst = connection.prepareStatement(SQLQueries.GET_RECEIPTS_ORDER_BY_DATE_ASC);
			}
			rs = pst.executeQuery();
			while (rs.next()) {
				receipts.add(mapReceipt(rs));
			}
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error getting receipts ordered by date!");
		} finally {
			DBManager.close(rs);
		}
		return receipts;
	}

	public static List<Receipt> getAllReceiptsOrderedByReceiptSum(boolean DESC) throws ReceiptException {
		connector = DBManager.getInstance();
		List<Receipt> receipts = new ArrayList<>();
		ResultSet rs = null;
		PreparedStatement pst = null;
		try (Connection connection = connector.getConnection()) {
			if (DESC) {
				pst = connection.prepareStatement(SQLQueries.GET_RECEIPTS_ORDER_BY_RECEIPT_SUM_DESC);
			} else {
				pst = connection.prepareStatement(SQLQueries.GET_RECEIPTS_ORDER_BY_RECEIPT_SUM_ASC);
			}
			rs = pst.executeQuery();
			while (rs.next()) {
				receipts.add(mapReceipt(rs));
			}
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error getting receipts ordered by date!");
		} finally {
			DBManager.close(pst);
			DBManager.close(rs);
		}
		return receipts;
	}

	public static List<Receipt> getAllReceiptsFilteredByMaster(long masterId) throws ReceiptException {
		connector = DBManager.getInstance();
		List<Receipt> receipts = new ArrayList<>();
		ResultSet rs = null;
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.GET_RECEIPTS_FILTERED_BY_ID_MASTER)) {
			pst.setLong(1, masterId);
			rs = pst.executeQuery();
			while (rs.next()) {
				receipts.add(mapReceipt(rs));
			}
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error getting receipts by master id = " + masterId);
		}
		return receipts;
	}

	public static void removeMasterByReceiptId(long id) throws ReceiptException {
		connector = DBManager.getInstance();
		try (Connection connection = connector.getConnection();
				PreparedStatement pst = connection.prepareStatement(SQLQueries.REMOVE_MASTER_BY_ID_RECEIPT)) {
			pst.setLong(1, id);
			pst.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
			throw new ReceiptException("Error removing master from receipt with id = " + id);
		}
	}
	
}
